# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --unshallow
    - name: Dokku Deploy action
      # You may pin to the exact commit or the version.
      # uses: idoberko2/dokku-deploy-github-action@4b326b36625e4a10add5f9601e8ffbaf048444b9
      
      uses: idoberko2/dokku-deploy-github-action@dd8a6aa3f08c890a24466a4dcd98165878fe3efb
      with:
        # The ssh private key to the dokku instance. WARNING: use a secret! Do not pass a plain text value!
        ssh-private-key: ${{secrets.SSH_KEY}}
        # The user to use for ssh (Default: dokku)
        dokku-user: dokku # optional, default is dokku
        # The dokku host to ssh into
        dokku-host: ${{secrets.HOST}}
        # The dokku app name
        app-name: fasbullah
        # The branch to push on the remote repository (Default: master)
        remote-branch: main # optional, default is master
        # Additional flags to be passed to the git push command. Could be used to force push
        git-push-flags: --force # optional, default is
